"""seed the catalog, its stock, and the promotion counter

Hand-written, not autogenerated: Alembic diffs schema, not data.

Revision ID: 0002_seed_catalog
Revises: b89d2968a2c4
"""

import sqlalchemy as sa
from alembic import op

revision = "0002_seed_catalog"
down_revision = "b89d2968a2c4"
branch_labels = None
depends_on = None

CATALOG = [
    ("tee-black", 25, 11),
    ("hoodie", 60, 34),
    ("poster", 10, 9),  # low margin: the flash-sale discount clamps here
]
STOCK = {"tee-black": 500, "hoodie": 200, "poster": 1000}


def upgrade() -> None:
    catalog = sa.table(
        "catalog",
        sa.column("sku", sa.String),
        sa.column("price", sa.Integer),
        sa.column("cost", sa.Integer),
    )
    inventory = sa.table(
        "inventory", sa.column("sku", sa.String), sa.column("qty", sa.Integer)
    )
    promo = sa.table("promo_spend", sa.column("id", sa.Integer), sa.column("spent", sa.Integer))

    op.bulk_insert(
        catalog,
        [{"sku": sku, "price": price, "cost": cost} for sku, price, cost in CATALOG],
    )
    op.bulk_insert(
        inventory, [{"sku": sku, "qty": qty} for sku, qty in STOCK.items()]
    )
    op.bulk_insert(promo, [{"id": 1, "spent": 0}])


def downgrade() -> None:
    op.execute("DELETE FROM promo_spend")
    op.execute("DELETE FROM inventory")
    op.execute("DELETE FROM catalog")
