"""initial schema

Revision ID: b89d2968a2c4
Revises: 
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = 'b89d2968a2c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.CheckConstraint('price >= cost', name='ck_catalog_above_cost'),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_unpublished', 'outbox', ['id'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    op.create_table('promo_spend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spent', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku'], ['catalog.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkouts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('detail', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku'], ['catalog.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.CheckConstraint('qty >= 0', name='ck_inventory_nonneg'),
    sa.ForeignKeyConstraint(['sku'], ['catalog.sku'], ),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('order_lines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku'], ['catalog.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_lines_sku', 'order_lines', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_lines_sku', table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_table('inventory')
    op.drop_table('checkouts')
    op.drop_table('carts')
    op.drop_table('promo_spend')
    op.drop_index('ix_outbox_unpublished', table_name='outbox', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('outbox')
    op.drop_table('catalog')
    # ### end Alembic commands ###
